export const ADJECTIVES: string[] = [
  'Ace', 'Agile', 'Alert', 'Amber', 'Ancient', 'Arctic', 'Ardent', 'Atomic',
  'Autumn', 'Azure', 'Blazing', 'Blithe', 'Bold', 'Bouncy', 'Brave', 'Breezy',
  'Bright', 'Brisk', 'Bronze', 'Calm', 'Candid', 'Caramel', 'Cheerful', 'Cherry',
  'Chill', 'Clever', 'Cloudy', 'Cobalt', 'Comet', 'Cool', 'Copper', 'Coral',
  'Cosmic', 'Crafty', 'Crisp', 'Cunning', 'Daring', 'Dazzling', 'Deep', 'Deft',
  'Deluxe', 'Diamond', 'Dizzy', 'Dusk', 'Dynamic', 'Eager', 'Early', 'Earthy',
  'Electric', 'Elite', 'Ember', 'Epic', 'Fabled', 'Fast', 'Fearless', 'Fierce',
  'Fiery', 'Fine', 'Flash', 'Flint', 'Fluffy', 'Flying', 'Frosty', 'Funky',
  'Galactic', 'Gallant', 'Gentle', 'Giant', 'Gilded', 'Gleaming', 'Glowing', 'Gold',
  'Grand', 'Grassy', 'Gritty', 'Happy', 'Hardy', 'Hazy', 'Hearty', 'Heavy',
  'Hidden', 'Hipster', 'Honest', 'Humble', 'Icy', 'Infinite', 'Iron', 'Ivory',
  'Jazzy', 'Jolly', 'Jovial', 'Joyful', 'Keen', 'Kind', 'Lanky', 'Laughing',
  'Lavender', 'Lean', 'Legendary', 'Light', 'Lively', 'Lucky', 'Lunar', 'Lusty',
  'Majestic', 'Mellow', 'Mighty', 'Mint', 'Misty', 'Muted', 'Mystic', 'Neon',
  'Noble', 'North', 'Obsidian', 'Odd', 'Olive', 'Onyx', 'Optic', 'Optimal',
  'Outlaw', 'Phantom', 'Plucky', 'Polished', 'Prime', 'Proud', 'Punchy', 'Quick',
  'Quiet', 'Radiant', 'Rapid', 'Raven', 'Ready', 'Rebel', 'Regal', 'Relentless',
  'Resilient', 'Roaring', 'Robust', 'Rocky', 'Royal', 'Ruby', 'Rustic', 'Sage',
  'Sandy', 'Sapphire', 'Sassy', 'Savage', 'Scarlet', 'Shadow', 'Sharp', 'Shiny',
  'Silent', 'Silver', 'Sleek', 'Slick', 'Smoky', 'Solar', 'Solid', 'Sonic',
  'Spark', 'Spectral', 'Speedy', 'Stellar', 'Storm', 'Sunny', 'Swift', 'Tangy',
  'Teal', 'Tenacious', 'Thunder', 'Tidal', 'Tiny', 'Titan', 'Topaz', 'Tropical',
  'Turbo', 'Twilight', 'Ultra', 'Unique', 'Valiant', 'Velvet', 'Vibrant', 'Vivid',
  'Wandering', 'Wild', 'Windy', 'Wiry', 'Wise', 'Witty', 'Zany', 'Zealous',
  'Zen', 'Zesty', 'Zippy',
]

export const ANIMALS: string[] = [
  'Albatross', 'Alligator', 'Alpaca', 'Antelope', 'Ape', 'Armadillo', 'Axolotl',
  'Badger', 'Bat', 'Bear', 'Beaver', 'Bison', 'Boar', 'Bobcat', 'Buffalo',
  'Capybara', 'Chameleon', 'Cheetah', 'Chinchilla', 'Chipmunk', 'Condor', 'Corgi',
  'Coyote', 'Crane', 'Crocodile', 'Crow', 'Dingo', 'Dolphin', 'Donkey', 'Dragonfly',
  'Duck', 'Eagle', 'Echidna', 'Elephant', 'Elk', 'Emu', 'Falcon', 'Ferret',
  'Flamingo', 'Fox', 'Frog', 'Gazelle', 'Gecko', 'Giraffe', 'Gnu', 'Goat',
  'Goose', 'Gorilla', 'Grizzly', 'Groundhog', 'Hamster', 'Hawk', 'Hedgehog',
  'Hippo', 'Horse', 'Hummingbird', 'Hyena', 'Ibis', 'Iguana', 'Jackal', 'Jaguar',
  'Jellyfish', 'Kangaroo', 'Kestrel', 'Kiwi', 'Koala', 'Komodo', 'Lemur', 'Leopard',
  'Lion', 'Lizard', 'Llama', 'Lobster', 'Lynx', 'Macaw', 'Manatee', 'Marmot',
  'Meerkat', 'Moose', 'Mongoose', 'Monkey', 'Moray', 'Moth', 'Mouse', 'Narwhal',
  'Newt', 'Numbat', 'Ocelot', 'Octopus', 'Okapi', 'Opossum', 'Orca', 'Ostrich',
  'Otter', 'Owl', 'Ox', 'Oyster', 'Panda', 'Panther', 'Parrot', 'Peacock',
  'Pelican', 'Penguin', 'Pheasant', 'Pig', 'Platypus', 'Polar', 'Porcupine',
  'Puffin', 'Quail', 'Quokka', 'Rabbit', 'Raccoon', 'Raven', 'Reindeer', 'Rhino',
  'Robin', 'Salamander', 'Seahorse', 'Seal', 'Shark', 'Sloth', 'Snail', 'Snake',
  'Sparrow', 'Spider', 'Squid', 'Squirrel', 'Stag', 'Starling', 'Swan', 'Tiger',
  'Toucan', 'Turtle', 'Vulture', 'Walrus', 'Warthog', 'Weasel', 'Wolf', 'Wolverine',
  'Wombat', 'Woodpecker', 'Yak', 'Zebra',
]
